- name: Copy sphinx conf
  template: src=sphinx_conf.j2 dest=/etc/sphinxsearch/sphinx.conf

- name: Make mailman search folder
  file: path=/var/lib/mailman/search owner=root group=www-data mode=0755 state=directory

- name: Make sphinx run folder
  file: path=/var/run/sphinxsearch owner=root group=root mode=0755 state=directory

- name: Copy sphinxpipe.py
  template: src=sphinxpipe.py.j2 dest=/var/lib/mailman/search/sphinxpipe.py mode=0755

- name: Copy sphinxsearch.py
  template: src=sphinxsearch.py.j2 dest=/var/lib/mailman/search/sphinxsearch.py mode=0755

- name: Copy archive template
  template: src=archtocnombox_html.j2 dest=/var/lib/mailman/templates/en/archtocnombox.html

- name: Start search-daemon
  shell: searchd

- name: Run indexer
  shell: sudo indexer --all --rotate

